serviceAccounts:
  alertmanager:
    create: false
  nodeExporter:
    create: true
  pushgateway:
    create: false
  server:
    create: true

alertmanager:
  enabled: false

server:
  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 30s
    ## How long until a scrape request times out
    ##
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 30s

  extraFlags:
    - web.enable-lifecycle
    - storage.tsdb.retention.size=${storage_retention}

  ingress:
    ## If true, Prometheus server Ingress will be created
    ##
    enabled: false

  persistentVolume:
    ## If true, Prometheus server will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

    existingClaim: "${pvc_name}"

  statefulSet:
    ## If true, use a statefulset instead of a deployment for pod management.
    ## This allows to scale replicas to more than 1 pod
    ##
    enabled: false

  ##
  retention: ""

pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false
