apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${service_name}-virtual-service
  namespace: ${namespace}
spec:
  hosts:
  - "${subdomain}.${domain}"
  gateways:
  - ${istio_ingress_gateway_name}
  http:
  - route:
    - destination:
        host: ${service_name}
        port:
          number: ${service_port}
